# Generated by Django 4.1.3 on 2022-11-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0002_research_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='image',
            field=models.ImageField(null=True, upload_to='researches/static/images'),
        ),
    ]
