# Generated by Django 4.1.3 on 2022-11-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0009_alter_research_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='image',
            field=models.ImageField(default='ldkjfaskfjd', upload_to='images'),
            preserve_default=False,
        ),
    ]
