# Generated by Django 4.1.3 on 2022-11-09 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0011_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='researches.user'),
            preserve_default=False,
        ),
    ]
